import { mountHeader, esc, label, money } from './ui.js';
import { toolHost } from './webmcp.js';
import { EventSession, buildEventReadyTools } from './eventready.js';
mountHeader('EventReady');
const $ = id => document.getElementById(id);
const slugs = ['green-fork','masa-y-mas','sweet-bench','casa-vieja','prime-platters','loop-rentals','handoff-staffing'];
const [vendors, demo, venue] = await Promise.all([Promise.all(slugs.map(slug => fetch(`/data/vendors/${slug}.json`).then(r => r.json()))),fetch('/data/event/demo-fundraiser.json').then(r => r.json()),fetch('/data/venues/riverside-hall.json').then(r => r.json())]);
const session = new EventSession({ vendors, demo, venue });
const badgeKind = status => status === 'covered' || status === 'ready' ? 'ok' : status === 'risk' ? 'risk' : 'blocker';
const briefInput = () => ({title:$('eventTitle').value,description:`${$('headcount').value} people, community fundraiser, $${$('budget').value} budget, ${$('vegetarian').value} vegetarians, ${$('vegan').value} vegan, ${$('glutenFree').value} gluten free, no kitchen at the venue`,headcount:Number($('headcount').value),budget:Number($('budget').value),serve_at:new Date($('serveAt').value).toISOString(),dietary:{vegetarian:Number($('vegetarian').value),vegan:Number($('vegan').value),gluten_free:Number($('glutenFree').value)}});
function render(state){
 const assessed=state.readiness.state!=='not_assessed'; $('workspace').hidden=!assessed; $('score').textContent=assessed?`${state.readiness.score}%`:'—'; $('readinessStamp').textContent=state.readiness.state.replaceAll('_',' ');
 $('readinessMessage').textContent=!assessed?'Run the assessment to find coverage gaps and unowned work.':state.readiness.state==='ready'?'Every blocking need is covered and every required job has an owner.':`${state.readiness.counts.blockers} blockers · ${state.readiness.counts.unowned} unowned jobs`;
 $('domainList').innerHTML=state.readiness.domains.map(d=>`<div class="domain-row"><span>${esc(d.label)}</span><span class="badge badge-${badgeKind(d.status)}">${esc(d.status.replaceAll('_',' '))}</span></div>`).join(''); if(!assessed)return;
 const ready=state.readiness.state==='ready'; $('stateBadge').className=`badge badge-${badgeKind(state.readiness.state)}`; $('stateBadge').textContent=ready?'Ready':state.readiness.state.replaceAll('_',' ');
 $('blockers').innerHTML=[...state.readiness.blockers.map(f=>`<div class="finding finding-blocker"><strong>Blocker</strong><span>${esc(f.message)}</span></div>`),...(state.readiness.counts.unowned?[`<div class="finding finding-owner"><strong>Ownership</strong><span>${state.readiness.counts.unowned} required jobs still need an explicit owner.</span></div>`]:[])].join('');
 $('options').innerHTML=state.options.map(o=>`<button class="option ${o.id===state.selectedOptionId?'option-selected':''}" data-option="${esc(o.id)}"><span><strong>${esc(o.label||o.id)}</strong>${o.recommended?'<em>recommended</em>':''}</span><small>${esc(o.summary)} · ${money(o.subtotal)}</small></button>`).join(''); $('serviceLevel').value=state.serviceLevel;
 const unresolved=state.readiness.responsibilities.filter(r=>r.status==='unresolved'); $('responsibilities').innerHTML=unresolved.length?unresolved.map(r=>`<div class="responsibility"><span><strong>${esc(label(r.resource))}</strong><small>${esc(r.when||'time not set')} · ${esc(r.evidence)}</small></span><button class="btn btn-quiet" data-assign="${esc(r.id)}">Assign to me</button></div>`).join(''):'<p class="all-owned">✓ Every required responsibility has an owner.</p>'; $('assignAll').hidden=!unresolved.length;
 $('delta').hidden=!state.delta?.lines?.length; $('delta').textContent=state.delta?.lines?.join(' ')||''; $('runStatus').textContent=ready?'READY · shareable':'DRAFT · blockers remain'; $('runIntro').textContent=ready?'A chronological handoff with an owner and evidence for every job.':'Resolve every blocker and owner before this becomes Ready.';
 $('runRows').innerHTML=state.runOfShow.rows.map(r=>`<div class="run-row"><span>${esc(r.at)}</span><span>${esc(r.action)}</span><span class="${r.owner==='Unassigned'?'tape':''}">${esc(r.owner)}</span><span>${esc(r.evidence)}</span></div>`).join(''); document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>session.selectPlan(b.dataset.option)); document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>session.assign(b.dataset.assign,'organizer','Event organizer'));
}
session.subscribe(render); render(session.snapshot());
for(const tool of buildEventReadyTools(session,render))toolHost().registerTool({...tool,execute:async input=>({content:[{type:'text',text:JSON.stringify(tool.run(input||{}))}]})});
$('assess').onclick=()=>{session.assess(briefInput());$('workspace').scrollIntoView({behavior:'smooth',block:'start'});}; $('serviceLevel').onchange=e=>session.changeServiceLevel(e.target.value); $('assignAll').onclick=()=>session.assignAll('organizer','Event organizer'); $('printRun').onclick=()=>window.print();
$('copyRun').onclick=async()=>{const run=session.runOfShow();const text=[`${run.event.title} — ${run.status.toUpperCase()}`,...run.rows.map(r=>`${r.at} | ${r.action} | ${r.owner} | ${r.evidence}`)].join('\n');try{await navigator.clipboard.writeText(text);$('copyRun').textContent='Copied';}catch{window.prompt('Copy the run of show:',text);}setTimeout(()=>{$('copyRun').textContent='Copy';},1500);};
