import { esc, label } from './ui.js';
import { toolHost } from './webmcp.js';
import { EventSession, buildEventReadyTools } from './eventready.js';
const $=id=>document.getElementById(id);
const slugs=['green-fork','masa-y-mas','sweet-bench','casa-vieja','prime-platters','loop-rentals','handoff-staffing'];
const [vendors,demo,venue]=await Promise.all([Promise.all(slugs.map(s=>fetch(`/data/vendors/${s}.json`).then(r=>r.json()))),fetch('/data/event/demo-fundraiser.json').then(r=>r.json()),fetch('/data/venues/riverside-hall.json').then(r=>r.json())]);
const session=new EventSession({vendors,demo,venue});

const categoryMeta={food:['Food & drinks','Dinner, dietary coverage, service and food safety','🍽'],venue:['Venue & access','Arrival windows, parking and room requirements','⌂'],equipment:['Equipment & setup','Tablescape, serving equipment and supplies','◇'],people:['Team & responsibilities','Vendors, volunteers and ownership','◎'],timing:['Schedule','Arrivals, setup, service and cleanup','◷'],budget:['Budget','Committed costs, allowances and contingency','$']};
function nextAction(row){return `<article class="next-action"><div class="action-icon">${categoryMeta[row.domain]?.[2]||'✓'}</div><div><span>${esc(categoryMeta[row.domain]?.[0]||'Plan')}</span><h3>${esc(label(row.resource))} needs an owner</h3><p>${esc(row.when||'Timing to confirm')} · Required by ${esc(row.evidence)}</p></div><button data-assign="${esc(row.id)}">Assign</button></article>`;}
function render(state){
 const ready=state.readiness.state==='ready', unresolved=state.readiness.responsibilities.filter(r=>r.status==='unresolved');
 $('decisionCount').textContent=unresolved.length+state.readiness.blockers.length; $('statusHero').className=`status-hero ${ready?'is-ready':'needs-attention'}`; $('statusTitle').textContent=ready?'Your event is ready':'Your event needs a few decisions'; $('statusSummary').textContent=ready?'Critical needs are covered, every required job has an owner, and your day-of plan is ready to share.':'Everything important is visible. Let’s close the gaps between your venue, vendors, and team.'; $('resolveWithAgent').hidden=ready;
 $('nextActions').innerHTML=ready?'<article class="ready-card"><span>✓</span><div><h3>Everything critical is covered</h3><p>Your next step is to share the day-of plan with your team.</p></div><button data-tab-jump="dayof">Open day-of plan</button></article>':unresolved.slice(0,3).map(nextAction).join('');
 $('planCategories').innerHTML=state.readiness.domains.map(d=>{const m=categoryMeta[d.id];const status=d.status==='covered'?'Complete':d.status==='not_applicable'?'On track':`${d.unowned+d.blockers} decisions`;return `<article class="category-card"><div class="category-icon">${m[2]}</div><div><h3>${m[0]}</h3><p>${m[1]}</p></div><span class="category-status ${d.status==='covered'?'complete':''}">${status}</span><button aria-label="Open ${m[0]}">→</button></article>`}).join('');
 const grouped={provider:state.readiness.responsibilities.filter(r=>r.owner==='provider'),organizer:state.readiness.responsibilities.filter(r=>r.owner==='organizer'),unassigned:unresolved}; $('teamList').innerHTML=[['Providers','Committed through vendor agreements',grouped.provider],['Roy · Organizer','Your assigned responsibilities',grouped.organizer],['Still unassigned','Decide who will own these',grouped.unassigned]].map(([name,sub,rows])=>`<article class="team-card"><header><div class="team-avatar">${name.slice(0,2).toUpperCase()}</div><div><h3>${name}</h3><p>${sub}</p></div><span>${rows.length} jobs</span></header><div>${rows.slice(0,8).map(r=>`<p><span>${esc(label(r.resource))}</span><small>${esc(r.when||'Confirm timing')}</small>${r.status==='unresolved'?`<button data-assign="${esc(r.id)}">Assign to Roy</button>`:'<i>✓</i>'}</p>`).join('')||'<p class="empty-team">No responsibilities here.</p>'}</div></article>`).join('');
 $('runHeading').textContent=ready?'Your event is ready to run':'Your working run-of-show'; $('runDescription').textContent=ready?'Every row has an owner and evidence from the event plan.':'This remains a draft until every critical need and responsibility is resolved.'; $('dayofBanner').className=`dayof-banner ${ready?'ready':''}`; $('dayofBanner').innerHTML=ready?'<span>Ready</span><p>Share this plan with your vendors and event team.</p>':'<span>Draft</span><p>Resolve the remaining decisions before sharing this with your team.</p>'; $('runRows').innerHTML=state.runOfShow.rows.map(r=>`<article><time>${esc(r.at)}</time><i></i><div><h3>${esc(r.action)}</h3><p>${esc(r.owner)} · ${esc(r.evidence)}</p></div></article>`).join('');
 document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>session.assign(b.dataset.assign,'organizer','Roy · Organizer')); bindJumps();
}
function activateTab(name){document.querySelectorAll('.workspace-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.workspace-view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'});}
function bindJumps(){document.querySelectorAll('[data-tab-jump]').forEach(b=>b.onclick=()=>activateTab(b.dataset.tabJump));}
document.querySelectorAll('.workspace-tab').forEach(b=>b.onclick=()=>activateTab(b.dataset.tab));bindJumps();
session.subscribe(render);session.assess();render(session.snapshot());
for(const tool of buildEventReadyTools(session,render))toolHost().registerTool({...tool,execute:async input=>({content:[{type:'text',text:JSON.stringify(tool.run(input||{}))}]})});

const showProposal=()=>{$('proposalModal').hidden=false;}; const hideProposal=()=>{$('proposalModal').hidden=true;}; $('resolveWithAgent').onclick=showProposal;$('reviewChanges').onclick=showProposal;$('closeProposal').onclick=hideProposal;$('cancelProposal').onclick=hideProposal;
$('applyProposal').onclick=()=>{session.changeServiceLevel('delivery');session.assignAll('organizer','Roy · Organizer');hideProposal();$('assistantMessages').innerHTML='<div class="assistant-message success"><span>✓ Changes applied</span><p>I switched catering to delivery and assigned the remaining operational work to Roy. The event is now ready, and I updated the day-of plan.</p></div><button class="assistant-cta" data-tab-jump="dayof">Open ready plan</button>';bindJumps();};
$('assignTeam').onclick=()=>session.assignAll('organizer','Roy · Organizer');
$('assistantInput').onkeydown=e=>{if(e.key==='Enter')$('sendAssistant').click();}; $('sendAssistant').onclick=()=>{const q=$('assistantInput').value.trim();if(!q)return;$('assistantMessages').insertAdjacentHTML('beforeend',`<div class="user-message">${esc(q)}</div><div class="assistant-message"><p>I can help with that. For this demo, try my recommended readiness plan to resolve the open operational work.</p></div>`);$('assistantInput').value='';};
$('newEvent').onclick=()=>{$('newEventModal').hidden=false;};$('closeNewEvent').onclick=$('cancelNewEvent').onclick=()=>{$('newEventModal').hidden=true;};$('closeAssistant').onclick=()=>document.querySelector('.assistant-panel').classList.toggle('collapsed');
$('printRun').onclick=()=>window.print();$('copyRun').onclick=async()=>{const run=session.runOfShow();const text=[`${run.event.title} — ${run.status.toUpperCase()}`,...run.rows.map(r=>`${r.at} | ${r.action} | ${r.owner}`)].join('\n');try{await navigator.clipboard.writeText(text);$('copyRun').textContent='Copied';}catch{window.prompt('Copy the day-of plan:',text);}setTimeout(()=>{$('copyRun').textContent='Copy plan';},1200);};
